alias _='sudo !!'
alias sl='ls'
alias ls='ls -atfFG'
alias grep='LANG=C ggrep --color=always'
alias grepr='grep -r'
alias ggrep='ggrep -nH'
alias vim='vim --noplugin'
alias cpa='rsync -poghb --backup-dir=/tmp/rsync -e /dev/null --progress --'